### ISSUE TITLE
docker compose problem 

### ISSUE THREAD

**Issue by tuppie333** [beak-insights/felicity-lims#28]
Hello! 
This projects looks perfect, thank you!
But I have some troubles with compose from Docker. 

```
=> CACHED [felicity_aio webapp-build 13/14] COPY ./*.json /app                                                    
=> CACHED [felicity_aio webapp-build 14/14] RUN pnpm webapp:build:only                                           
=> CACHED [felicity_aio server-aio 8/9] COPY --from=webapp-build /app/dist /app/felicity/templates/static            
=> ERROR [felicity_aio server-aio 9/9] RUN cd /app/felicity && alembic upgrade head                             
------
 > [felicity_aio server-aio 9/9] RUN cd /app/felicity && alembic upgrade head:
1.075 Traceback (most recent call last):
1.075   File "/usr/local/bin/alembic", line 8, in <module>
1.075     sys.exit(main())
1.075   File "/usr/local/lib/python3.10/site-packages/alembic/config.py", line 641, in main
1.076     CommandLine(prog=prog).main(argv=argv)
1.076   File "/usr/local/lib/python3.10/site-packages/alembic/config.py", line 631, in main
1.076     self.run_cmd(cfg, options)
1.076   File "/usr/local/lib/python3.10/site-packages/alembic/config.py", line 608, in run_cmd
1.076     fn(
1.076   File "/usr/local/lib/python3.10/site-packages/alembic/command.py", line 403, in upgrade
1.076     script.run_env()
1.076   File "/usr/local/lib/python3.10/site-packages/alembic/script/base.py", line 583, in run_env
1.076     util.load_python_file(self.dir, "env.py")
1.076   File "/usr/local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
1.076     module = load_module_py(module_id, path)
1.076   File "/usr/local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
1.077     spec.loader.exec_module(module)  # type: ignore
1.077   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
1.077   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
1.077   File "/app/felicity/migrations/env.py", line 9, in <module>
1.077     from felicity.database.base import DBModel
1.077   File "/app/felicity/../felicity/database/base.py", line 1, in <module>
1.077     from felicity.apps.analysis.models.analysis import Analysis  # noqa
1.077   File "/app/felicity/../felicity/apps/__init__.py", line 7, in <module>
1.078     from felicity.apps.audit.mixin import AuditableMixin
1.078   File "/app/felicity/../felicity/apps/audit/mixin.py", line 9, in <module>
1.078     from felicity.apps.audit.models import AuditLog
1.078   File "/app/felicity/../felicity/apps/audit/models.py", line 6, in <module>
1.078     from felicity.database.base_class import DBModel
1.078   File "/app/felicity/../felicity/database/base_class.py", line 3, in <module>
1.078     from typing import Any, AsyncIterator, List, Optional, Self
1.078 ImportError: cannot import name 'Self' from 'typing' (/usr/local/lib/python3.10/typing.py)
------
failed to solve: process "/bin/sh -c cd /app/felicity && alembic upgrade head" did not complete successfully: exit code: 1
```

**Comment by aurthurm** [comment]
Hie your typing extensions must be outdated. You might need try `pip install typing-extensions --upgrade`

Or Simply add  typing-extensions to  requirements.txt and rebuild
```txt
requirements.txt file
...
...
...
psycopg2==2.9.9
typing-extensions
```

**Comment by aurthurm** [comment]
Hie.

I fixed this with https://github.com/beak-insights/felicity-lims/commit/ae7e1d3c351dd0fd783f7edbb3a045ba8632a04
