### ISSUE TITLE
Api Errors during docker installation

### ISSUE THREAD

**Issue by jp-pelegrino** [beak-insights/felicity-lims#39]
It is running on a 4 core; 16 GB ram to mitigate this repeating error:
`[1] [ERROR] Worker (pid:44) was sent SIGKILL! Perhaps out of memory?`

But new issues arrises:

```
felicity_api  | INFO:root:Initialising felicity workforce ...
felicity_api  | INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
felicity_api  | INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
felicity_api  | INFO:apscheduler.scheduler:Added job "run_jobs_if_exists" to job store "default"
felicity_api  | INFO:apscheduler.scheduler:Added job "prepare_for_impress" to job store "default"
felicity_api  | INFO:apscheduler.scheduler:Scheduler started
felicity_api  | [2024-08-30 01:57:48 +0000] [10] [ERROR] Traceback (most recent call last):
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/redis/asyncio/connection.py", line 276, in connect
felicity_api  |     await self.retry.call_with_retry(
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/redis/asyncio/retry.py", line 59, in call_with_retry
felicity_api  |     return await do()
felicity_api  |            ^^^^^^^^^^
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/redis/asyncio/connection.py", line 682, in _connect
felicity_api  |     reader, writer = await asyncio.open_connection(
felicity_api  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
felicity_api  |   File "/usr/local/lib/python3.12/asyncio/streams.py", line 48, in open_connection
felicity_api  |     transport, _ = await loop.create_connection(
felicity_api  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
felicity_api  |   File "uvloop/loop.pyx", line 2039, in create_connection
felicity_api  |   File "uvloop/loop.pyx", line 2016, in uvloop.loop.Loop.create_connection
felicity_api  | ConnectionRefusedError: [Errno 111] Connection refused
felicity_api  |
felicity_api  | During handling of the above exception, another exception occurred:
felicity_api  |
felicity_api  | Traceback (most recent call last):
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 738, in lifespan
felicity_api  |     async with self.lifespan_context(app) as maybe_state:
felicity_api  |   File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
felicity_api  |     return await anext(self.gen)
felicity_api  |            ^^^^^^^^^^^^^^^^^^^^^
felicity_api  |   File "/app/felicity/lims/boot.py", line 37, in lifespan
felicity_api  |     await broadcast.connect()
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/broadcaster/_base.py", line 70, in connect
felicity_api  |     await self._backend.connect()
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/broadcaster/_backends/redis.py", line 22, in connect
felicity_api  |     await self._pubsub.connect()
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/redis/asyncio/client.py", line 864, in connect
felicity_api  |     self.connection = await self.connection_pool.get_connection(
felicity_api  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/redis/asyncio/connection.py", line 1049, in get_connection
felicity_api  |     await self.ensure_connection(connection)
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/redis/asyncio/connection.py", line 1082, in ensure_connection
felicity_api  |     await connection.connect()
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/redis/asyncio/connection.py", line 284, in connect
felicity_api  |     raise ConnectionError(self._error_message(e))
felicity_api  | redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
felicity_api  |
felicity_api  | [2024-08-30 01:57:48 +0000] [10] [ERROR] Application startup failed. Exiting.
felicity_api  | [2024-08-30 01:57:48 +0000] [10] [INFO] Worker exiting (pid: 10)
felicity_api  | [2024-08-30 01:57:48 +0000] [8] [INFO] Started server process [8]
felicity_api  | [2024-08-30 01:57:48 +0000] [8] [INFO] Waiting for application startup.
felicity_api  | INFO:root:Initialising felicity workforce ...
felicity_api  | INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
felicity_api  | INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
felicity_api  | INFO:apscheduler.scheduler:Added job "run_jobs_if_exists" to job store "default"
felicity_api  | INFO:apscheduler.scheduler:Added job "prepare_for_impress" to job store "default"
felicity_api  | INFO:apscheduler.scheduler:Scheduler started
felicity_api  | [2024-08-30 01:57:48 +0000] [8] [ERROR] Traceback (most recent call last):
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/redis/asyncio/connection.py", line 276, in connect
felicity_api  |     await self.retry.call_with_retry(
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/redis/asyncio/retry.py", line 59, in call_with_retry
felicity_api  |     return await do()
felicity_api  |            ^^^^^^^^^^
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/redis/asyncio/connection.py", line 682, in _connect
felicity_api  |     reader, writer = await asyncio.open_connection(
felicity_api  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
felicity_api  |   File "/usr/local/lib/python3.12/asyncio/streams.py", line 48, in open_connection
felicity_api  |     transport, _ = await loop.create_connection(
felicity_api  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
felicity_api  |   File "uvloop/loop.pyx", line 2039, in create_connection
felicity_api  |   File "uvloop/loop.pyx", line 2016, in uvloop.loop.Loop.create_connection
felicity_api  | ConnectionRefusedError: [Errno 111] Connection refused
felicity_api  |
felicity_api  | During handling of the above exception, another exception occurred:
felicity_api  |
felicity_api  | Traceback (most recent call last):
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 738, in lifespan
felicity_api  |     async with self.lifespan_context(app) as maybe_state:
felicity_api  |   File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
felicity_api  |     return await anext(self.gen)
felicity_api  |            ^^^^^^^^^^^^^^^^^^^^^
felicity_api  |   File "/app/felicity/lims/boot.py", line 37, in lifespan
felicity_api  |     await broadcast.connect()
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/broadcaster/_base.py", line 70, in connect
felicity_api  |     await self._backend.connect()
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/broadcaster/_backends/redis.py", line 22, in connect
felicity_api  |     await self._pubsub.connect()
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/redis/asyncio/client.py", line 864, in connect
felicity_api  |     self.connection = await self.connection_pool.get_connection(
felicity_api  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/redis/asyncio/connection.py", line 1049, in get_connection
felicity_api  |     await self.ensure_connection(connection)
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/redis/asyncio/connection.py", line 1082, in ensure_connection
felicity_api  |     await connection.connect()
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/redis/asyncio/connection.py", line 284, in connect
felicity_api  |     raise ConnectionError(self._error_message(e))
felicity_api  | redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
felicity_api  |
felicity_api  | [2024-08-30 01:57:48 +0000] [8] [ERROR] Application startup failed. Exiting.
felicity_api  | [2024-08-30 01:57:48 +0000] [8] [INFO] Worker exiting (pid: 8)
felicity_api  | [2024-08-30 01:57:50 +0000] [1] [ERROR] Worker (pid:7) exited with code 3
felicity_api  | [2024-08-30 01:57:50 +0000] [1] [ERROR] Worker (pid:10) was sent SIGTERM!
felicity_api  | --- Logging error ---
felicity_api  | [2024-08-30 01:57:50 +0000] [1] [ERROR] Worker (pid:9) was sent SIGTERM!
felicity_api  | Traceback (most recent call last):
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/arbiter.py", line 209, in run
felicity_api  |     self.sleep()
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/arbiter.py", line 360, in sleep
felicity_api  |     ready = select.select([self.PIPE[0]], [], [], 1.0)
felicity_api  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
felicity_api  |     self.reap_workers()
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/arbiter.py", line 530, in reap_workers
felicity_api  |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
felicity_api  | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
felicity_api  |
felicity_api  | During handling of the above exception, another exception occurred:
felicity_api  |
felicity_api  | Traceback (most recent call last):
felicity_api  |   File "/usr/local/lib/python3.12/logging/__init__.py", line 1163, in emit
felicity_api  |     stream.write(msg + self.terminator)
felicity_api  | RuntimeError: reentrant call inside <_io.BufferedWriter name='<stderr>'>
felicity_api  |
felicity_api  | During handling of the above exception, another exception occurred:
felicity_api  |
felicity_api  | Traceback (most recent call last):
felicity_api  |   File "/usr/local/lib/python3.12/logging/__init__.py", line 1163, in emit
felicity_api  |     stream.write(msg + self.terminator)
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
felicity_api  |     self.reap_workers()
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/arbiter.py", line 554, in reap_workers
felicity_api  |     self.log.error(msg)
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/glogging.py", line 272, in error
felicity_api  |     self.error_log.error(msg, *args, **kwargs)
felicity_api  |   File "/usr/local/lib/python3.12/logging/__init__.py", line 1568, in error
felicity_api  |     self._log(ERROR, msg, args, **kwargs)
felicity_api  |   File "/usr/local/lib/python3.12/logging/__init__.py", line 1684, in _log
felicity_api  |     self.handle(record)
felicity_api  |   File "/usr/local/lib/python3.12/logging/__init__.py", line 1700, in handle
felicity_api  |     self.callHandlers(record)
felicity_api  |   File "/usr/local/lib/python3.12/logging/__init__.py", line 1762, in callHandlers
felicity_api  |     hdlr.handle(record)
felicity_api  |   File "/usr/local/lib/python3.12/logging/__init__.py", line 1028, in handle
felicity_api  |     self.emit(record)
felicity_api  |   File "/usr/local/lib/python3.12/logging/__init__.py", line 1168, in emit
felicity_api  |     self.handleError(record)
felicity_api  |   File "/usr/local/lib/python3.12/logging/__init__.py", line 1081, in handleError
felicity_api  |     sys.stderr.write('--- Logging error ---\n')
felicity_api  | RuntimeError: reentrant call inside <_io.BufferedWriter name='<stderr>'>
felicity_api  | Call stack:
felicity_api  |   File "/usr/local/bin/gunicorn", line 8, in <module>
felicity_api  |     sys.exit(run())
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
felicity_api  |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/app/base.py", line 236, in run
felicity_api  |     super().run()
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/app/base.py", line 72, in run
felicity_api  |     Arbiter(self).run()
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/arbiter.py", line 229, in run
felicity_api  |     self.halt(reason=inst.reason, exit_status=inst.exit_status)
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/arbiter.py", line 342, in halt
felicity_api  |     self.stop()
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/arbiter.py", line 396, in stop
felicity_api  |     time.sleep(0.1)
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
felicity_api  |     self.reap_workers()
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/arbiter.py", line 554, in reap_workers
felicity_api  |     self.log.error(msg)
felicity_api  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/glogging.py", line 272, in error
felicity_api  |     self.error_log.error(msg, *args, **kwargs)
felicity_api  | Message: 'Worker (pid:10) was sent SIGTERM!'
felicity_api  | Arguments: ()
felicity_api  | [2024-08-30 01:58:20 +0000] [1] [ERROR] Shutting down: Master
felicity_api  | [2024-08-30 01:58:20 +0000] [1] [ERROR] Reason: Worker failed to boot.
felicity_api exited with code 0
```

**Comment by jp-pelegrino** [comment]
I also created a new instance but the more noticeable error was the 
`redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.`

This happens when using the `felicity_static_nginx` preset

**Comment by aurthurm** [comment]
The production docker is out of date. let me update it and revert back

**Comment by jp-pelegrino** [comment]
> The production docker is out of date. let me update it and revert back

I am now getting 502 Gateway errors

the second command for docker when using the `felicity-aio-nginx` , `"felicity-lims upgrade"` only works when the preset is `felicity-aio`

```
root@core ~/felicity-lims# docker compose -f docker-compose.prod.yml exec felicity-aio-nginx bash -c "felicity-lims upgrade"
WARN[0000] /root/felicity-lims/docker-compose.prod.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
bash: line 1: felicity-lims: command not found
root@core ~/felicity-lims# docker compose -f docker-compose.prod.yml exec felicity-aio bash -c "felicity-lims upgrade"
WARN[0000] /root/felicity-lims/docker-compose.prod.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 6f377b641bc8, init
INFO  [alembic.runtime.migration] Running upgrade 6f377b641bc8 -> e598ed62784d, removed-date_generated
INFO  [alembic.runtime.migration] Running upgrade e598ed62784d -> 28042fd2e903, removed-auditlog
INFO  [alembic.runtime.migration] Running upgrade 28042fd2e903 -> 10ecf5ec9e80, updated
INFO  [alembic.runtime.migration] Running upgrade 10ecf5ec9e80 -> 92f0866a8101, its me
INFO  [alembic.runtime.migration] Running upgrade 92f0866a8101 -> 2d4b2acdf75f, its me again
Upgraded to revision: head
```

Additionally, these are the logs from the **`felicity-aio`**

```
root@core ~/felicity-lims# docker compose -f docker-compose.prod.yml logs felicity-aio -f -n100
WARN[0000] /root/felicity-lims/docker-compose.prod.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
felicity-aio  | INFO:root:Initialising felicity workforce ...
felicity-aio  | INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
felicity-aio  | INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
felicity-aio  | INFO:apscheduler.scheduler:Added job "run_jobs_if_exists" to job store "default"
felicity-aio  | INFO:apscheduler.scheduler:Added job "prepare_for_impress" to job store "default"
felicity-aio  | INFO:apscheduler.scheduler:Scheduler started
felicity-aio  | [2024-09-03 18:24:44 +0000] [592] [INFO] Application startup complete.
felicity-aio  | [2024-09-03 18:24:44 +0000] [591] [INFO] Started server process [591]
felicity-aio  | [2024-09-03 18:24:44 +0000] [591] [INFO] Waiting for application startup.
felicity-aio  | INFO:root:Initialising felicity workforce ...
felicity-aio  | INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
felicity-aio  | INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
felicity-aio  | INFO:apscheduler.scheduler:Added job "run_jobs_if_exists" to job store "default"
felicity-aio  | INFO:apscheduler.scheduler:Added job "prepare_for_impress" to job store "default"
felicity-aio  | INFO:apscheduler.scheduler:Scheduler started
felicity-aio  | [2024-09-03 18:24:44 +0000] [591] [INFO] Application startup complete.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 1s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 1s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 1s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 1s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 2s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 2s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 2s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 2s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 4s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 4s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 4s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 4s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 8s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 8s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 8s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 8s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 16s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 16s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 16s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 16s.
felicity-aio  | [2024-09-03 18:25:15 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:591)
felicity-aio  | [2024-09-03 18:25:15 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:592)
felicity-aio  | [2024-09-03 18:25:15 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:593)
felicity-aio  | [2024-09-03 18:25:15 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:594)
felicity-aio  | [2024-09-03 18:25:20 +0000] [1] [ERROR] Worker (pid:593) was sent SIGKILL! Perhaps out of memory?
felicity-aio  | [2024-09-03 18:25:20 +0000] [663] [INFO] Booting worker with pid: 663
felicity-aio  | [2024-09-03 18:25:22 +0000] [1] [ERROR] Worker (pid:591) was sent SIGKILL! Perhaps out of memory?
felicity-aio  | [2024-09-03 18:25:22 +0000] [664] [INFO] Booting worker with pid: 664
felicity-aio  | [2024-09-03 18:25:23 +0000] [1] [ERROR] Worker (pid:594) was sent SIGKILL! Perhaps out of memory?
felicity-aio  | [2024-09-03 18:25:23 +0000] [1] [ERROR] Worker (pid:592) was sent SIGKILL! Perhaps out of memory?
felicity-aio  | [2024-09-03 18:25:23 +0000] [665] [INFO] Booting worker with pid: 665
felicity-aio  | [2024-09-03 18:25:23 +0000] [666] [INFO] Booting worker with pid: 666
felicity-aio  | [2024-09-03 18:25:26 +0000] [663] [INFO] Started server process [663]
felicity-aio  | [2024-09-03 18:25:26 +0000] [663] [INFO] Waiting for application startup.
felicity-aio  | INFO:root:Initialising felicity workforce ...
felicity-aio  | INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
felicity-aio  | INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
felicity-aio  | INFO:apscheduler.scheduler:Added job "run_jobs_if_exists" to job store "default"
felicity-aio  | INFO:apscheduler.scheduler:Added job "prepare_for_impress" to job store "default"
felicity-aio  | INFO:apscheduler.scheduler:Scheduler started
felicity-aio  | [2024-09-03 18:25:26 +0000] [663] [INFO] Application startup complete.
felicity-aio  | [2024-09-03 18:25:28 +0000] [664] [INFO] Started server process [664]
felicity-aio  | [2024-09-03 18:25:28 +0000] [664] [INFO] Waiting for application startup.
felicity-aio  | INFO:root:Initialising felicity workforce ...
felicity-aio  | INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
felicity-aio  | INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
felicity-aio  | INFO:apscheduler.scheduler:Added job "run_jobs_if_exists" to job store "default"
felicity-aio  | INFO:apscheduler.scheduler:Added job "prepare_for_impress" to job store "default"
felicity-aio  | INFO:apscheduler.scheduler:Scheduler started
felicity-aio  | [2024-09-03 18:25:28 +0000] [664] [INFO] Application startup complete.
felicity-aio  | [2024-09-03 18:25:29 +0000] [665] [INFO] Started server process [665]
felicity-aio  | [2024-09-03 18:25:29 +0000] [665] [INFO] Waiting for application startup.
felicity-aio  | INFO:root:Initialising felicity workforce ...
felicity-aio  | INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
felicity-aio  | INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
felicity-aio  | INFO:apscheduler.scheduler:Added job "run_jobs_if_exists" to job store "default"
felicity-aio  | INFO:apscheduler.scheduler:Added job "prepare_for_impress" to job store "default"
felicity-aio  | INFO:apscheduler.scheduler:Scheduler started
felicity-aio  | [2024-09-03 18:25:29 +0000] [665] [INFO] Application startup complete.
felicity-aio  | [2024-09-03 18:25:29 +0000] [666] [INFO] Started server process [666]
felicity-aio  | [2024-09-03 18:25:29 +0000] [666] [INFO] Waiting for application startup.
felicity-aio  | INFO:root:Initialising felicity workforce ...
felicity-aio  | INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
felicity-aio  | INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
felicity-aio  | INFO:apscheduler.scheduler:Added job "run_jobs_if_exists" to job store "default"
felicity-aio  | INFO:apscheduler.scheduler:Added job "prepare_for_impress" to job store "default"
felicity-aio  | INFO:apscheduler.scheduler:Scheduler started
felicity-aio  | [2024-09-03 18:25:29 +0000] [666] [INFO] Application startup complete.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 1s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 1s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 1s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 1s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 2s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 2s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 2s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 2s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 4s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 4s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 4s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 4s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 8s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 8s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 8s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 8s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 16s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 16s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 16s.
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 16s.
felicity-aio  | [2024-09-03 18:25:57 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:663)
felicity-aio  | [2024-09-03 18:25:59 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:664)
felicity-aio  | [2024-09-03 18:25:59 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:665)
felicity-aio  | [2024-09-03 18:25:59 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:666)
```

**Comment by aurthurm** [comment]
I have update the docker production template

use this preset: felicity-static-nginx
